sudo: true
language: java
install: true
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
#    - os: osx

sudo: required

before_install:
  - ./start-broker.sh

script:
  - mvn -B clean -q
  - mvn -B --projects org.eclipse.paho.client.mqttv3,org.eclipse.paho.client.mqttv3.test test -q
  - mvn -B --projects org.eclipse.paho.mqttv5.common,org.eclipse.paho.mqttv5.client test -q

#addons:
#  apt:
#    sources:
#      - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
#    packages:
#      - mosquitto
